# Generated by Django 4.0.4 on 2022-05-01 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixas',
            fields=[
                ('atualiza', models.DateTimeField(auto_created=True, auto_now=True)),
                ('data', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'caixas',
            },
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('atualiza', models.DateTimeField(auto_created=True, auto_now=True)),
                ('data', models.DateTimeField(auto_created=True)),
                ('champs_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('kit_id', models.CharField(max_length=6)),
                ('nida', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casos',
            },
        ),
        migrations.CreateModel(
            name='Extracao_Ordem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'extracao_ordem',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Amostra',
            fields=[
                ('atualiza', models.DateTimeField(auto_created=True, auto_now=True)),
                ('data', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipo_amostras',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('atualiza', models.DateTimeField(auto_created=True, auto_now=True)),
                ('data', models.DateTimeField(auto_created=True)),
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=4)),
                ('tipo_amostras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.tipo_amostra')),
            ],
            options={
                'db_table': 'specimen',
            },
        ),
        migrations.CreateModel(
            name='DNA_Extraido',
            fields=[
                ('atualiza', models.DateTimeField(auto_created=True, auto_now=True)),
                ('data', models.DateTimeField(auto_created=True)),
                ('specimenid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dna_repetido', models.BooleanField(default=False)),
                ('posicao', models.PositiveSmallIntegerField()),
                ('ordem_extracao', models.PositiveSmallIntegerField()),
                ('posicao_anterior', models.PositiveSmallIntegerField()),
                ('repetir', models.BooleanField(default=False)),
                ('processado', models.BooleanField(default=False)),
                ('processado_nr', models.PositiveSmallIntegerField()),
                ('acabou', models.BooleanField(default=False)),
                ('acabou_nr', models.PositiveSmallIntegerField(default=0)),
                ('dna_perdido', models.BooleanField(default=False)),
                ('reporte', models.TextField(blank=True, null=True)),
                ('data_perdida_notificacao', models.DateField()),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_caixa', to='armazem.caixas')),
                ('caixa_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_caixa_anterior', to='armazem.caixas')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.casos')),
                ('extracao_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.extracao_ordem')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.specimen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dna_extraido',
            },
        ),
        migrations.AddField(
            model_name='caixas',
            name='specimen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.specimen'),
        ),
        migrations.CreateModel(
            name='Amostra_Original',
            fields=[
                ('criado', models.DateTimeField(auto_created=True)),
                ('specimenid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('posicao', models.PositiveSmallIntegerField()),
                ('posicao_anterior', models.PositiveSmallIntegerField()),
                ('extraido', models.BooleanField(default=False)),
                ('extracao_nr', models.PositiveSmallIntegerField(default=0)),
                ('processado', models.BooleanField(default=False)),
                ('acabou', models.BooleanField(default=False)),
                ('acabou_nr', models.PositiveSmallIntegerField(default=0)),
                ('amostra_perdida', models.BooleanField(default=False)),
                ('reporte', models.TextField(blank=True, null=True)),
                ('data_perdida_notificacao', models.DateField()),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.caixas')),
                ('caixa_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixa_anterior', to='armazem.caixas')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.casos')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazem.specimen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'amostra_original',
            },
        ),
    ]
