palavras = {
    'ad': 'Ad.',
    'ad_estudante': 'Ad. Estudante',
    'ad_familiar': 'Ad. Familiar',
    'ad_funcionario': 'Ad. Funcionário',
    'ad_professor': 'Ad. Professor',
    'adicionar': 'adicionar',
    'admin': 'administrador',
    'administracao': 'administração',
    'admissao': 'admissão',
    'amostra': 'amostra(s)',
    'antibiotico': 'antibiótico(s)',
    'armazem': 'armazem(s)',
    'atendidos': 'atendidos',
    'atraso': 'atraso(s)',
    'aulas': 'aulas',
    'avaliar': 'avaliar',
    'aviado': 'aviado(s)',
    'bem_vindo': 'bem vindo',
    'cartao': 'cartão',
    'cientifica': 'científica',
    'codigo': 'codigo(s)',
    'com': 'com',
    'complem': 'complementares',
    'conta': 'Conta',
    'contacto': 'contacto(s)',
    'contabilidade': 'contabilidade',
    'curricular': 'curricular',
    'cursos': 'curso(s)',
    'da': 'da',
    'dar_entr_rec': 'dar entrada de receita',
    'de': 'de',
    'definicoes': 'definições',
    'descricao': 'descrição',
    'desempenho': 'desempenho',
    'direcao':'direcção',
    'disciplinas': 'disciplinas',
    'doc': 'doc',
    'documento': 'documento(s)',
    'doenca': 'doença(s)',
    'doenca_max_acom': 'doenças mais acometidas',
    'doenca_min_acom': 'doenças menos acometidas',
    'droga': 'droga(s)',
    'educandos': 'educando(s)',
    'em': 'em',
    'empresa_criadora': 'netavel',
    'encontrar': 'encontrar',
    'especial': 'Especial',
    'estado': 'estado',
    'exame': 'Exame(s)',
    'existente': 'existente',
    'extraviado': 'extraviado(s)',
    'eventos': 'Eventos',
    'farmacia': 'farmácia(s)',
    'familiar': 'Familiar',
    'feitas': 'Feitas',
    'feminino': 'Feminino',
    'funcionarios': 'Funcionário(s)',
    'genero': 'género',
    'geral': 'geral',
    'healthcare': 'Health-Care',
    'humanos': 'humanos',
    'idiomas': 'Idioma(s)',
    'imprimir': 'Imprimir',
    'inexistente': 'inexistente',
    'inicio': 'Início',
    'inscricao': 'Inscrição',
    'ir': 'ir',
    'isolado': 'isolado(s)',
    'laboratorio': 'laboratório(s)',
    'lista': 'lista',
    'listas': 'listas',
    'login': 'Login',
    'logout': 'Terminar sessão',
    'masculino': 'Masculino',
    'medicamento': 'medicamento(s)',
    'meus': 'Meus',
    'modo': 'modo',
    'mudar': 'Mudar',
    'navegacao': 'navegação',
    'novo': 'novo',
    'novos': 'novos',
    'nota': 'Nota(s)',
    'paciente': 'paciente',
    'pacientes': 'pacientes',
    'pac_atendidos': 'pacientes atendidos',
    'pac_em_atendimento': 'pacientes em atendimento',
    'pagamentos': 'Pagamento(s)',
    'patogeno': 'patogeno(s)',
    'pendentes': 'pendentes',
    'perdida': 'perdida(s)',
    'perdido': 'perdido(s)',
    'perfil': 'Perfil',
    'periodo': 'periodo',
    'pesquisar': 'Pesquisar',
    'plan_curri': 'Plano(s) Curricular(es)',
    'plan_disci': 'Plano(s) Disciplinar(es)',
    'planos': 'Plano(s)',
    'por': 'por',
    'prescricao': 'prescrição',
    'prescrito': 'prescrito(s)',
    'prescrever': 'prescrever',
    'pre_inscri': 'Pré-Inscrição',
    'procurar': 'procurar',
    'proc_paciente': 'procurar paciente',
    'produto': 'produto(s)',
    'receita': 'receita',
    'rec_pend': 'receitas pendentes',
    'recursos': 'recursos',
    'realizados': 'realizado(s)',
    'recebida': 'recebida(s)',
    'recebido': 'recebido(s)',
    'requisicao': 'requisição',
    'requisicoes': 'requisições',
    'requisitado': 'requisitado(s)',
    'requisitar': 'requisitar',
    'resistente': 'resistente(s)',
    'resultado': 'resultado(s)',
    'res_lib': 'resultados liberados',
    'saida': 'saida',
    'saidas': 'saidas',
    'salvar': 'salvar',
    'secretaria': 'Secretaria',
    'sector': 'sector',
    'sectores': 'sectores',
    'senha': 'Senha',
    'sensivel': 'sensível',
    'sinais': 'sinais',
    'sintomas': 'sintomas',
    'sitename': 'Health-Care',
    'situao_financ': 'Situação Financeira',
    'stock': 'stock',
    'susceptibilidade': 'susceptibilidade',
    'teste': 'teste',
    'testes': 'Teste(s)',
    'tipo': 'tipo',
    'titulo': 'akademya',
    'tsa': 'TSA',
    'turma': 'turma(s)',
    'unidade': 'unidade(s)',
    'usuarios': 'Usuário(s)',
    'ver': 'ver',
    'website_url': 'http://127.0.0.1:8006',
}
