# Generated by Django 4.0.4 on 2022-05-01 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Ativacao',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_cod', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=8)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_ativacao',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('lingua', models.CharField(default='universal', max_length=10, primary_key=True, serialize=False)),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to='idioma')),
            ],
            options={
                'db_table': 'idioma',
            },
        ),
        migrations.CreateModel(
            name='Nomes',
            fields=[
                ('nome', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nomes',
            },
        ),
        migrations.CreateModel(
            name='Senha_Redefinir',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('senha_cod', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'senha_redefinir',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_lang', models.CharField(blank=True, max_length=5, null=True)),
                ('nome', models.CharField(max_length=75)),
                ('nivel', models.IntegerField()),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.idioma')),
            ],
            options={
                'db_table': 'tipo_de_usuario',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('tipo_usuario', models.ManyToManyField(related_name='tipo_de_usuario', to='contas.tipo_usuario')),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cod_lang', models.CharField(blank=True, max_length=5, null=True)),
                ('nome', models.CharField(max_length=15)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.idioma')),
            ],
            options={
                'db_table': 'ocupacao',
            },
        ),
    ]
